class Utility{

  static const String
                      geoDataHotelsInNation ="/geoDataHotelsInNation",
                      wordCountPositive = "/wordCountPositive",
                      wordCountNegative = "/wordCountNegative",
                      coppieHotelPunteggioMedioPerNazione = "/coppieHotelPunteggioMedioPerNazione",
                      recensioniHotelDallaData = "/recensioniHotelDallaData",
                      coppieHotel_NegReviews = "/coppieHotel_NegReviews",
                      coppieHotel_PosReviews = "/coppieHotel_PosReviews",
                      averageScoreFilter = "/averageScoreFilter",
                      reviewsNumberFilter = "/reviewsNumberFilter",
                      naiveBayesian = "/naiveBayesian",
                      timeScoreEvolution = "/timeScoreEvolution",
                      timeScoreEvolutionMonth = "/timeScoreEvolutionMonth",
                      allFilters = "/allFilters",
                      demandingClients = "/demandingClientsPerNationality";


  static const List<String> points = <String>['1','2','3','4','5','6','7','8','9','10'];

  static const List<String> nations = <String>[
    'Russia',
    'Germany',
    'United Kingdom',
    'France',
    'Italy',
    'Spain',
    'Ukraine',
    'Poland',
    'Romania',
    'Netherlands',
    'Belgium',
    'Czech Republic',
    'Greece',
    'Portugal',
    'Sweden',
    'Hungary',
    'Belarus',
    'Austria',
    'Serbia',
    'Switzerland',
    'Bulgaria',
    'Denmark',
    'Finland',
    'Slovakia',
    'Norway',
    'Ireland',
    'Croatia',
    'Moldova',
    'Bosnia and Herzegovina',
    'Albania',
    'Lithuania',
    'North Macedonia',
    'Slovenia',
    'Latvia',
    'Estonia',
    'Montenegro',
    'Luxembourg',
    'Malta',
    'Iceland',
    'Andorra',
    'Monaco',
    'Liechtenstein',
    'San Marino',
    'Holy See'
  ];

  static const String server = "localhost:8080";

  static const List<String> hotels = <String>[
    'Hotel Vienna',
    'Hotel Palace GL',
    'B Montmartre',
    'Corinthia Hotel London',
    'Twenty Nevern Square Hotel',
    'Hotel Wagner',
    'The Langham London',
    'Hotel Cambon',
    'Hotel Serhs Rivoli Rambla',
    'Park Avenue Baker Street',
    'Best Western Atlantic Hotel',
    'Hotel Parc Saint Severin Esprit de France',
    'The Sumner Hotel',
    'Garden Elys e',
    'La Suite West Hyde Park',
    'Pulitzer Amsterdam',
    'Hilton London Angel Islington',
    'H tel Baume',
    'Sheraton Diana Majestic',
    'Antares Hotel Accademia',
    'Radisson Blu Edwardian Mercer Street',
    'Wilson Boutique Hotel',
    'Best Western Seraphine Kensington Olympia',
    'Novotel Suites Paris Expo Porte de Versailles',
    'Threadneedles Autograph Collection',
    'Catalonia Plaza Catalunya',
    'Hotel Plaza Elys es',
    'Acta Atrium Palace',
    'Hotel Berna',
    'Doubletree by Hilton London Kensington',
    'H tel Amastan Paris',
    'Mercure Paris Opera Grands Boulevards',
    'Le Meridien Piccadilly',
    'Club Quarters Hotel St Paul s',
    'The Mandeville Hotel',
    'Club Quarters Hotel Trafalgar Square',
    'Urban Lodge Hotel',
    'Catalonia Born',
    'H tel des Champs Elys es',
    'L Hotel Pergol se Paris',
    'Millennium Hotel London Mayfair',
    'Hyatt Regency Paris Etoile',
    'Hotel Santa Marta Suites',
    'St James Hotel Club Mayfair',
    'New Linden Hotel',
    'Hotel Eitlj rg',
    'Suites H tel Helzear Champs Elys es',
    'Napoleon Paris',
    'Exe Vienna',
    'Henley House Hotel',
    'United Lodge Hotel and Apartments',
    'H tel Elysees Mermoz',
    'Apex City Of London Hotel',
    'Pullman Paris Centre Bercy',
    'Austria Trend Hotel Schloss Wilhelminenberg Wien',
    'Les Jardins Du Marais',
    'Hotel Indigo Paris Opera',
    'Elys es R gencia',
    'Hotel La Spezia Gruppo MiniHotel',
    'H tel F licien by Elegancia',
    'Best Western Premier Faubourg 88',
    'Plaza Tour Eiffel',
    'Hotel Mediolanum',
    'Hilton London Metropole',
    'Royal Hotel Champs Elys es',
    'Radisson Blu Edwardian Bloomsbury Street',
    'Mercure Paris 15 Porte de Versailles',
    'Haymarket Hotel',
    'Carlyle Brera Hotel',
    'Hotel Alimara',
    'Eurostars Embassy',
    'Hotel Amadeus',
    'The Ampersand Hotel',
    'Fairmont Rey Juan Carlos I',
    'Schlosshotel R mischer Kaiser',
    'The Chesterfield Mayfair',
    'Crowne Plaza London Docklands',
    'Mercure Paris Notre Dame Saint Germain des Pr s',
    'Morgan Mees',
    'Vilana Hotel',
    'Hotel Royal Elys es',
    'Hotel Ares Eiffel',
    'LaGare Hotel Milano Centrale MGallery by Sofitel',
    'Hotel Corvinus',
    'Sofitel Legend The Grand Amsterdam',
    'Mercure Paris Porte d Orleans',
    'Flemings Mayfair',
    'Newhotel Roblin',
    'Barcelona Hotel Colonial',
    'The Westin Palace',
    'H tel Ad le Jules',
    'Mercure Paris Tour Eiffel Pont Mirabeau',
    'Hotel SB Diagonal Zero Barcelona 4 Sup',
    'Derby Alma',
    'Hotel Margot House',
    'W12 Rooms',
    'W Barcelona',
    'Mercure Paris Montmartre Sacr Coeur',
    'H tel Thoumieux',
    'Hotel 55',
    'Hotel Carrobbio',
    'Rathbone',
    'Park Grand Paddington Court',
    'Petit Palace Barcelona',
    'Karma Sanctum Soho Hotel',
    'Hotel le Lapin Blanc',
    'Best Western Plus Hotel Galles',
    'Tryp Barcelona Apolo Hotel',
    'Das Opernring Hotel',
    'Hotel du Petit Moulin',
    'H tel Monna Lisa Champs Elys es',
    'Millennium Gloucester Hotel London',
    'FourSide Hotel Vienna City Center',
    'Hilton London Wembley',
    'The Dylan Amsterdam',
    '11 Cadogan Gardens',
    'H tel Da Vinci Spa',
    'Style Hotel',
    'Hilton London Canary Wharf',
    'COQ Hotel Paris',
    'Novotel Paris Centre Tour Eiffel',
    'Grand Ferdinand Vienna Your Hotel In The City Center',
    'Grupotel Gran Via 678',
    'Hotel SB Icaria Barcelona',
    'Le Marcel',
    'Senato Hotel Milano',
    'DO CO Hotel Vienna',
    'Hotel Le Saint Gregoire',
    'The Levin Hotel',
    'Rosewood London',
    'Hotel Trianon Rive Gauche',
    'Sina The Gray',
    'citizenM Amsterdam',
    'H10 London Waterloo',
    'Shepherd s Bush Boutique Hotel',
    'Waldorf Astoria Amsterdam',
    'Hotel Murmuri Barcelona',
    'Mercure Paris Bastille Saint Antoine',
    'Rydges Kensington Hotel',
    'Hotel G tico',
    'WestCord Art Hotel Amsterdam 4 stars',
    'Palazzo Parigi Hotel Grand Spa Milano',
    'Arion Cityhotel Vienna und Appartements',
    'Hotel degli Arcimboldi',
    'Hotel City Central',
    'Hotel V Fizeaustraat',
    'The Grand at Trafalgar Square',
    'H tel De Buci by MH',
    'Pershing Hall',
    'Le Pavillon de la Reine Spa',
    'Hotel Boltzmann',
    'City Rooms',
    'Leonardo Hotel Milan City Center',
    'Axel Hotel Barcelona Urban Spa Adults Only',
    'Grand Hotel Wien',
    'Hotel Vueling Bcn by HC',
    'Hotel Le 10 BIS',
    'ABaC Restaurant Hotel Barcelona GL Monumento',
    'Courtyard by Marriott Amsterdam Arena Atlas',
    'Terrass H tel Montmartre by MH',
    'Mandarin Oriental Hyde Park London',
    'The Capital',
    'Le Grand H tel de Normandie',
    'Milan Marriott Hotel',
    'H tel Waldorf Trocad ro',
    'Ilunion Barcelona',
    'TH Street Duomo',
    'Mondrian London',
    'Atala Champs Elys es',
    'citizenM London Shoreditch',
    'The Waldorf Hilton',
    'Prince de Galles a Luxury Collection hotel Paris',
    'The Harmonie Vienna',
    'The Nadler Kensington',
    'Number Sixteen',
    'Le Pigalle Hotel',
    'Conrad London St James',
    'UNA Hotel Scandinavia',
    'AC Hotel Diagonal L Illa a Marriott Lifestyle Hotel',
    'Hotel Magna Pars Small Luxury Hotels of the World',
    'Grange St Paul s Hotel',
    'Hotel Casa Fuster G L Monumento',
    'Hotel D Este',
    'Relais Christine',
    'Holiday Inn Amsterdam Arena Towers',
    'Hotel Les Rives de Notre Dame',
    'Novotel London Excel',
    'The Arch London',
    'Park Hyatt Vienna',
    'Henry VIII',
    'Melia Paris Tour Eiffel',
    'Ca Bianca Hotel Corte Del Naviglio',
    'Hotel Imperial A Luxury Collection Hotel',
    'La Villa Royale',
    'City Hotel Deutschmeister',
    'Hotel Miramar Barcelona GL',
    'Hallmark Hotel London Chigwell Prince Regent',
    'Rocco Forte Brown s Hotel',
    'Hotel Vittoria',
    'H tel Gustave',
    'Ofelias Hotel 4 Sup',
    'Holiday Inn Vienna City',
    'ADI Doria Grand Hotel',
    'H tel Keppler',
    'Grosvenor House A JW Marriott Hotel',
    'AC Hotel Barcelona Forum a Marriott Lifestyle Hotel',
    'Palais Hansen Kempinski Vienna',
    'Hotel Vignon',
    'Hotel Mozart',
    'La Villa Haussmann',
    'Novotel London City South',
    'Novotel Paris 14 Porte d Orl ans',
    'Relais Du Louvre',
    'Pertschy Palais Hotel',
    'Meli Milano',
    'Hotel Lombardia',
    'Hampshire Hotel The Manor Amsterdam',
    'Hazlitt s',
    'Aparthotel Arai 4 Superior',
    'Grange Beauchamp Hotel',
    'Ashburn Hotel',
    'Apollofirst Boutique Hotel',
    'Hotel JL No76',
    'My Chelsea',
    'The Wittmore Adults Only',
    'M by Montcalm Shoreditch London Tech City',
    'NH Hesperia Barcelona del Mar',
    'NH Amsterdam Caransa',
    'Austria Trend Hotel Park Royal Palace Vienna',
    'Platine Hotel Spa',
    'Hotel Best Western PLUS Alfa Aeropuerto',
    'Mercure Wien Zentrum',
    'Novotel Amsterdam City',
    'Fletcher Hotel Amsterdam',
    'Op ra Marigny',
    'The Gore Hotel Starhotels Collezione',
    'Park Plaza County Hall London',
    'Hollmann Beletage Design Boutique',
    'Ambassade Hotel',
    'London Suites',
    'The One Barcelona GL',
    'Amadi Park Hotel',
    'Barcel Sants',
    'Petit Palace Museum',
    'The Athenaeum',
    'Eurostars Angli',
    'London Marriott Hotel Kensington',
    'Onix Liceo',
    'Roomz Vienna',
    'Falkensteiner Hotel Wien Margareten',
    'Royal Ramblas',
    'Rainers Hotel Vienna',
    'Thistle Euston',
    'The Park Tower Knightsbridge a Luxury Collection Hotel',
    'Best Western Amiral Hotel',
    'H tel Mayfair Paris',
    'London Bridge Hotel',
    'Der Wilhelmshof',
    'Negresco Princess 4 Sup',
    'H10 Urquinaona Plaza',
    'Ibis Styles Milano Palmanova',
    'Hotel mbit Barcelona',
    'The Rembrandt',
    'Expo Hotel Barcelona',
    'MiHotel',
    'Olivia Plaza Hotel',
    'Aparthotel Mariano Cubi Barcelona',
    'Pakat Suites Hotel',
    'AC Hotel Irla a Marriott Lifestyle Hotel',
    'Bcn Urban Hotels Gran Rosellon',
    'Copthorne Tara Hotel London Kensington',
    'Nu Hotel',
    'Hotel Mentana',
    'Hotel 82 London',
    'H tel De Vend me',
    'Hotel Astor Saint Honor ',
    'Hotel Gran Derby Suites',
    'Hotel Saint Dominique',
    'H tel Recamier',
    'Sofitel Vienna Stephansdom',
    'IntercityHotel Wien',
    'H tel des Ducs D Anjou',
    'Gran Hotel La Florida',
    'Hotel Atmospheres',
    'Le Lavoisier',
    'Majestic Hotel Spa',
    'Paris Marriott Champs Elysees Hotel',
    'Hotel Garbi Millenni',
    'Le Meurice',
    'Shaftesbury Hyde Park International',
    'Dorsett Shepherds Bush',
    'Arthotel ANA Westbahn',
    'Hotel Montalembert',
    'Hotel Daniel Vienna',
    'Sir Adam Hotel',
    'Worldhotel Cristoforo Colombo',
    'Park Plaza London Park Royal',
    'H10 Cubik 4 Sup',
    'DoubleTree by Hilton Amsterdam Centraal Station',
    'Grand Royale London Hyde Park',
    'Le Tsuba Hotel',
    'DoubleTree By Hilton Milan',
    'H tel Madison by MH',
    'Pullman Paris Tour Eiffel',
    'H tel Original Paris',
    'Hotel Michelangelo',
    'NH Collection Milano President',
    'Four Seasons Hotel Milano',
    'Goralska R sidences H tel Paris Bastille',
    'The Grosvenor',
    'Best Western Aulivia Op ra',
    'The Savoy',
    'BEST WESTERN PLUS Amedia Wien',
    'Park Plaza Victoria Amsterdam',
    'Mercure London Hyde Park',
    'Starhotels Anderson',
    'The Bryson Hotel',
    'Shaftesbury Metropolis London Hyde Park',
    'Andreola Central Hotel',
    'Mokinba Hotels Baviera',
    'H tel Le Relais Saint Germain',
    'Hotel de Seze',
    'Best Western Tour Eiffel Invalides',
    'Crowne Plaza London Kensington',
    'Great Northern Hotel A Tribute Portfolio Hotel London',
    'Ohla Barcelona',
    'Austria Trend Hotel Doppio Wien',
    'Hotel Am Konzerthaus Vienna MGallery by Sofitel',
    'Holiday Inn London Wembley',
    'Hotel Imlauer Wien',
    'The Level at Melia Barcelona Sky',
    'Hotel Stendhal Place Vend me Paris MGallery by Sofitel',
    'Zenit Barcelona',
    'Hilton London Tower Bridge',
    'Royal Saint Michel',
    'DoubleTree by Hilton London Ealing',
    'Duquesa Suites Barcelona',
    'Hotel Cavendish',
    'Baglioni Hotel Carlton The Leading Hotels of the World',
    'DoubleTree by Hilton London Islington',
    'Novotel Suites Paris Nord 18 me',
    'Best Western Plus Hotel Blue Square',
    'Hotel K nig von Ungarn',
    'The Academy',
    'Mercure London Kensington Hotel',
    'The Chelsea Harbour Hotel',
    'Best Western Palm Hotel',
    'Le M ridien Barcelona',
    'Maison Albar H tel Paris Champs Elys es ex Mac Mahon ',
    'Hotel Villa Lafayette Paris IX',
    'Bulgari Hotel Milano',
    'Acca Palace',
    'Milan Suite Hotel',
    'Madeleine Plaza',
    'Le Metropolitan a Tribute Portfolio Hotel',
    'Derag Livinghotel Kaiser Franz Joseph Vienna',
    'Hotel Sunflower',
    'Sansi Diputacio',
    'Club Quarters Hotel Lincoln s Inn Fields',
    'H tel Diva Opera',
    'Best Western Premier Hotel Couture',
    'Silken Concordia',
    'Best Western Premier Marais Grands Boulevards',
    'Shangri La Hotel at The Shard London',
    'Legend Saint Germain by Elegancia',
    'NH Sants Barcelona',
    'Novotel Paris 17',
    'Simply Rooms Suites',
    'Radisson Blu Edwardian Grafton',
    'Paris Marriott Opera Ambassador Hotel',
    'La Maison Favart',
    'Hotel du Louvre in the Unbound Collection by Hyatt',
    'Catalonia Rigoletto',
    'La Villa des Ternes',
    'Bilderberg Garden Hotel',
    'Le Parisis Paris Tour Eiffel',
    'Millennium Copthorne Hotels at Chelsea Football Club',
    'Danubius Hotel Regents Park',
    'Catalonia Park Putxet',
    'Best Western Antares Hotel Concorde',
    'Dukes Hotel',
    'The Park Grand London Paddington',
    'The Zetter Townhouse Clerkenwell',
    'Best Western Maitrise Hotel Edgware Road',
    'H tel Beauchamps',
    'Eurostars Ramblas',
    'Maison Albar Hotel Paris C line',
    'Hotel Capricorno',
    'Hotel J ger',
    'ARCOTEL Wimberger',
    'TownHouse Duomo',
    'Bulgari Hotel London',
    'Condes de Barcelona',
    'The Tower A Guoman Hotel',
    'Le Marceau Bastille',
    'Ayre Hotel Caspe',
    'H tel Montmartre Mon Amour',
    'Les Jardins De La Villa Spa',
    'Silken Gran Hotel Havana',
    'Aparthotel Atenea Barcelona',
    'Pol Grace Hotel',
    'Hotel Bristol A Luxury Collection Hotel',
    'Old Ship Inn Hackney',
    'H tel San R gis',
    'Etoile Saint Ferdinand',
    'Hotel Le Placide Saint Germain Des Pr s',
    'The Rookery',
    'Austria Trend Hotel Astoria Wien',
    'De L Europe Amsterdam',
    'H tel de Lille',
    'Novotel Milano Linate Aeroporto',
    'Hotel Bachaumont',
    'Mercure Paris Gare De Lyon TGV',
    'H tel Raphael',
    '1K Hotel',
    'Crowne Plaza London The City',
    'Hotel Champs Elys es Friedland by Happyculture',
    'Hilton London Kensington Hotel',
    'H tel Horset Op ra Best Western Premier Collection',
    'Novotel Paris Gare De Lyon',
    'Imperial Riding School Renaissance Vienna Hotel',
    'Boundary Rooms Suites',
    'Hotel Milano Scala',
    'Batty Langley s',
    'H tel Victor Hugo Paris Kl ber',
    'K K Hotel Maria Theresia',
    'Hotel Panache',
    'Holiday Inn London West',
    'Best Western Paris Gare Saint Lazare',
    'Hotel Bristol',
    'Hotel Am Schubertring',
    'Doubletree By Hilton London Greenwich',
    'Warwick Paris Former Warwick Champs Elysees ',
    'Hotel Arkadenhof',
    'Hotel Op ra Richepanse',
    'H10 Metropolitan 4 Sup',
    'Hotel Eden',
    'Hotel De Vigny',
    'Mayflower Hotel Apartments',
    'The Westbridge Hotel',
    'NH Milano Grand Hotel Verdi',
    'Sall s Hotel Pere IV',
    'Aparthotel Adagio Vienna City',
    'Norfolk Towers Paddington',
    'Hotel Moonlight',
    'H tel Barri re Le Fouquet s',
    'Hotel Sans Souci Wien',
    'Maison Borella',
    'Novotel London Canary Wharf',
    'The Abbey Court Notting Hill',
    'Hotel Plaza Athenee Paris',
    'Hotel Cavour',
    'Innkeeper s Lodge London Greenwich',
    'NH Hesperia Barcelona Presidente',
    'Le G n ral H tel',
    'Hotel Boutique Duomo',
    'DoubleTree By Hilton London Excel',
    'Best Western Premier Hotel Dante',
    'Hilton Vienna Plaza',
    'Hotel Mercure Wien City',
    'Blakemore Hyde Park',
    'Hotel Wandl',
    'Hotel Clerici',
    'Hotel Les Bains Paris',
    'Novotel Paris Vaugirard Montparnasse',
    'Grand Hotel Downtown',
    'The Chess Hotel',
    'Melia White House Hotel',
    'Mercure Paris Bastille Marais',
    'Le Burgundy Paris',
    'H tel Le Walt',
    'Melia Paris Vendome',
    'The Levante Parliament A Design Hotel',
    'St James Court A Taj Hotel London',
    'Dikker en Thijs Fenice Hotel',
    'Conservatorium Hotel',
    'H tel Crayon Rouge by Elegancia',
    'Trinit Haussmann',
    'Hotel Silver',
    'Washington Mayfair Hotel',
    'Villa Alessandra',
    'Silken Ramblas',
    'NH Milano Touring',
    'Hotel Rekord',
    'Georgian House Hotel',
    'Best Western Le 18 Paris',
    'IH Hotels Milano Lorenteggio',
    'The Beaufort',
    'Hampshire Hotel Amsterdam American',
    'W London Leicester Square',
    'Room Mate Anna',
    'Hotel Manzoni',
    'Best Western The Boltons Hotel London Kensington',
    'Sina De La Ville',
    'Amarante Beau Manoir',
    'The Principal London',
    'Hotel Mademoiselle',
    'STRAF a Member of Design Hotels ',
    'L H tel',
    'Melia Paris Champs Elys es',
    'Rubens At The Palace',
    'Antica Locanda Dei Mercanti',
    'Park Plaza Victoria London',
    'DoubleTree by Hilton London Chelsea',
    'H tel du Minist re',
    'Best Western Mercedes Arc de Triomphe',
    'La Chambre du Marais',
    'NH Amsterdam Museum Quarter',
    'Hotel Malte Astotel',
    'Palais Coburg Residenz',
    'Grand Hotel Central',
    'Radisson Blu Style Hotel Vienna',
    'Canal House',
    'The Justin James Hotel',
    'Hotel Louis 2',
    'Hotel Carlton s Montmartre',
    'Hotel Barcelona Catedral',
    'Hotel Tiziano Park Vita Parcour Gruppo MiniHotels',
    'Hotel Tocq',
    'Petit Palace Boqueria Garden',
    'Hotel Ciutadella Barcelona',
    'St Pancras Renaissance Hotel London',
    'Novotel London Blackfriars',
    'Renaissance Barcelona Hotel',
    'Best Western Allegro Nation',
    'Hilton London Green Park',
    'Golden Tulip Bercy Gare de Lyon 209',
    'Barcel Raval',
    'Hotel Barcelona Universal',
    'Landmark London',
    'Hotel Esther a',
    'San Domenico House',
    'H tel De Sers Champs Elys es Paris',
    'Hotel Kavalier',
    'Holiday Inn London Whitechapel',
    'The Zetter Townhouse Marylebone',
    'Victoire Germain',
    'H10 Universitat',
    'Majestic Hotel Spa Barcelona GL',
    'UNA Hotel Mediterraneo',
    'Mandarin Oriental Milan',
    'Mercure Paris Opera Louvre',
    'Hotel Am Parkring',
    'H tel de la Bourdonnais',
    'XO Hotel',
    'Jumeirah Lowndes Hotel',
    'Intercontinental London The O2',
    'Franklin Roosevelt',
    'Britannia International Hotel Canary Wharf',
    'Hotel Eiffel Blomet',
    'Park International Hotel',
    'H tel Bedford',
    'Mercure Paris Terminus Nord',
    'Monument Hotel',
    'Ayre Hotel Gran V a',
    'The Guesthouse Vienna',
    'Covent Garden Hotel',
    'Acevi Villarroel',
    'Hotel Le Mareuil',
    'The Hoxton Shoreditch',
    'NH Carlton Amsterdam',
    'Holiday Inn London Regent s Park',
    'Hotel Schild',
    'Corus Hotel Hyde Park',
    'Eccleston Square Hotel',
    'Comfort Inn Suites Kings Cross St Pancras',
    'Best Western Bretagne Montparnasse',
    'Splendide Royal Paris',
    'Hotel Monsieur',
    'Catalonia Barcelona Plaza',
    'Castille Paris Starhotels Collezione',
    'Room Mate Carla',
    'Austria Trend Hotel Savoyen Vienna',
    'Olivia Balmes Hotel',
    'Hotel DO Pla a Reial G L ',
    'Le Pavillon des Lettres',
    'Hotel Des Saints Peres Esprit de France',
    'Bilderberg Hotel Jan Luyken',
    'South Place Hotel',
    'Hotel Bagu s',
    'Dutch Design Hotel Artemis',
    'Novotel London Greenwich',
    'Paris Marriott Rive Gauche Hotel',
    'Courthouse Hotel London',
    'Element Amsterdam',
    'Hotel Scribe Paris Opera by Sofitel',
    'Park Hotel',
    'The Park City Grand Plaza Kensington Hotel',
    'The Kings Head Hotel',
    'Starhotels Business Palace',
    'IH Hotels Milano Gioia',
    'Mercure Paris 19 Philharmonie La Villette',
    'Alma Barcelona GL',
    'Hotel Villa Saxe Eiffel',
    'Hotel Indigo Barcelona Plaza Catalunya',
    'DoubleTree by Hilton Hotel London Tower of London',
    'Holiday Inn London Mayfair',
    'InterContinental Amstel Amsterdam',
    'Best Western Premier Louvre Saint Honor ',
    'Eurohotel Diagonal Port',
    'Sheraton Grand London Park Lane',
    'Belfast',
    'Hotel V Nesplein',
    'Pullman London St Pancras',
    'Suite Hotel 900 m zur Oper',
    'Boutique H tel Konfidentiel',
    'H tel Lancaster Paris Champs Elys es',
    'Radisson Blu Edwardian Hampshire',
    'Ham Yard Hotel',
    'Holiday Inn Paris Gare Montparnasse',
    'Hotel Nestroy Wien',
    'H tel Brighton Esprit de France',
    'Mercure Vienna First',
    'Best Western Hotel Mirage',
    'Grange Langham Court Hotel',
    'Am Spiegeln',
    'Kube Hotel Ice Bar',
    'Vincci Bit',
    'M venpick Hotel Amsterdam City Centre',
    'Hotel Arena',
    'Hotel Roemer Amsterdam',
    'Mercure Paris 17 me Saint Lazare Monceau',
    'The Toren',
    'L Empire Paris',
    'London Marriott Maida Vale',
    'Inntel Hotels Amsterdam Centre',
    'Windsor Opera',
    'Royal Garden Champs Elysees',
    'Mercure Secession Wien',
    'Holiday Inn Paris Elys es',
    'Ambassadors Bloomsbury',
    'Hotel Le Sainte Beuve',
    'ARCOTEL Kaiserwasser Superior',
    'H tel Mansart Esprit de France',
    'Grange Strathmore Hotel',
    'The Rockwell',
    'Grosvenor House Suites by Jumeirah Living',
    'Radisson Blu Edwardian Berkshire',
    'Arthotel ANA Prime',
    'The Queens Gate Hotel',
    'Lancaster London',
    'TRYP Paris Op ra',
    'Evenia Rossello',
    'Hotel Pulitzer',
    'Hilton London Bankside',
    'Hilton Paris Opera',
    'H tel Le M',
    'Okko Hotels Paris Porte De Versailles',
    'Hotel Indigo London Tower Hill',
    'Portobello House',
    'NH Danube City',
    'The Tophams Hotel',
    'Hotel Landhaus Fuhrgassl Huber',
    'The Westin Paris Vend me',
    'One Aldwych',
    'Brunelleschi Hotel',
    'Mercure Hotel Raphael Wien',
    'Amsterdam Canal Residence',
    'Hotel Kaiserin Elisabeth',
    'Park Plaza Vondelpark Amsterdam',
    'Park Grand London Hyde Park',
    'Le Senat',
    'AC Hotel Paris Porte Maillot by Marriott',
    'Hotel Le Six',
    'Amba Hotel Marble Arch',
    'Hotel Sacher Wien',
    'Grange Fitzrovia Hotel',
    'Blakes Hotel',
    'The Henrietta Hotel',
    'Hotel Sezz Paris',
    'UNA Hotel Cusani',
    'First Hotel Paris Tour Eiffel',
    'H10 Marina Barcelona',
    'Jaz Amsterdam',
    'NH Collection Amsterdam Barbizon Palace',
    'The Connaught',
    'St George Hotel',
    'Radisson Blu Edwardian Kenilworth',
    'Mercure Paris Op ra Faubourg Montmartre',
    'Hotel Pierre Milano',
    'H tel Powers',
    'Best Western Premier Le Swann',
    'citizenM Tower of London',
    'H10 Art Gallery 4 Sup',
    'Catalonia Barcelona 505',
    'Hotel Espa a Ramblas',
    'The Dorchester Dorchester Collection',
    'The Portobello Hotel',
    'A La Villa Madame',
    'H tel Moli re',
    'Best Western Premier Kaiserhof Wien',
    'London Elizabeth Hotel',
    'The Drayton Court Hotel',
    'Best Western Madison Hotel',
    'Villa d Estr es',
    'Fleming s Conference Hotel Wien',
    'H tel California Champs Elys es',
    'Melia Vienna',
    'TownHouse 33',
    'Hampton by Hilton Amsterdam Centre East',
    'Abba Sants',
    'Les Matins de Paris Spa',
    'Hotel Le petit Paris',
    'Hotel Midmost',
    'Grand Hotel Amr th Amsterdam',
    'Villa Panth on',
    'The Belgrave Hotel',
    'Clayton Crown Hotel London',
    'Hotel Capitol Milano',
    'Hotel Villa Emilia',
    'Guitart Grand Passage',
    'Lansbury Heritage Hotel',
    'Hotel des Tuileries Relais du Silence',
    'Best Western Premier Op ra Faubourg Ex Hotel Jules ',
    'Hotel Casa Camper',
    'AC Hotel Sants a Marriott Lifestyle Hotel',
    'Hotel Odeon Saint Germain',
    'Millennium Hotel London Knightsbridge',
    'Hotel Opera Cadet',
    'Hotel Abbot',
    'Holiday Inn Paris Notre Dame',
    'Seven Hotel',
    'Charlotte Street Hotel',
    'Austria Trend Hotel Europa Wien',
    'Courtyard by Marriott Vienna Prater Messe',
    'Hotel La Villa Saint Germain Des Pr s',
    'London Marriott Hotel Park Lane',
    'Holiday Inn Paris Op ra Grands Boulevards',
    'Melia Paris Notre Dame',
    'NH Amsterdam Noord',
    'Hotel Eug ne en Ville',
    'H tel D Aubusson',
    'BoB Hotel by Elegancia',
    'Marlin Waterloo',
    'Saint Georges Hotel',
    'NH Collection Wien Zentrum',
    'Splendid Etoile',
    'Grange Holborn Hotel',
    'Park Inn by Radisson Uno City Vienna',
    'The Student Hotel Amsterdam City',
    'London Hilton on Park Lane',
    '9Hotel Republique',
    'FourSide Hotel Suites Vienna',
    'Amba Hotel Charing Cross',
    'Graben Hotel',
    'Catalonia La Pedrera',
    'Apollo Hotel Amsterdam',
    'Mercure Paris Arc de Triomphe Etoile',
    'Ayre Hotel Rosell n',
    'Catalonia Catedral',
    'NH City Centre Amsterdam',
    'Apex Temple Court Hotel',
    'Novotel Barcelona City',
    'Hotel Louvre Montana',
    'Residence Henri IV',
    'Hilton Vienna',
    'Park Plaza London Waterloo',
    'Hotel Ambassador',
    'Luxury Suites Amsterdam',
    'Crowne Plaza Amsterdam South',
    'Novotel Milano Nord Ca Granda',
    'The Victoria',
    'London Marriott Hotel Regents Park',
    'Atahotel Contessa Jolanda',
    'Sanderson A Morgans Hotel',
    'Holiday Inn Paris Montmartre',
    'Staunton Hotel B B',
    'Glam Milano',
    'H tel Chaplain Paris Rive Gauche',
    'Park Plaza London Riverbank',
    'Mercure Paris Bercy Biblioth que',
    'Alexandra Barcelona A DoubleTree by Hilton',
    'St Martins Lane A Morgans Original',
    'Mercure London Bloomsbury Hotel',
    'Catalonia Square 4 Sup',
    'Maison Albar Hotel Paris Op ra Diamond',
    'Admiral Hotel',
    'Bermondsey Square Hotel A Bespoke Hotel',
    'The Hari London',
    'Hilton Diagonal Mar Barcelona',
    'London Marriott Hotel Grosvenor Square',
    'Millennium Hotel Paris Opera',
    'Ilunion Almirante',
    'Sercotel Amister Art Hotel Barcelona',
    'TownHouse 12',
    'COMO The Halkin',
    'The Montague On The Gardens',
    'The Nadler Victoria',
    'Hotel Verneuil Saint Germain',
    'Falkensteiner Hotel Wien Zentrum Schottenfeld',
    'Best Western Plus Elys e Secret',
    'Hotel du Vin Cannizaro House Wimbledon',
    'My Home In Paris',
    'Mercure Paris Gare Montparnasse',
    'TheWesley',
    'H tel France d Antin Op ra',
    'The Laslett',
    'Best Western Premier Kapital Op ra',
    'The Royal Park Hotel',
    'MARQUIS Faubourg St Honor Relais Ch teaux',
    'Duret',
    'The College Hotel',
    'Hotel Rathaus Wein Design',
    'Hotel Well and Come',
    'Hotel Les Bulles De Paris',
    'H tel R de Paris Boutique Hotel',
    'Small Luxury Hotel Altstadt Vienna',
    'H10 Casa Mimosa 4 Sup',
    'Hotel Monge',
    'Best Western Premier Op ra Opal',
    'NH Milano Palazzo Moscova',
    'The Leonard Hotel',
    'Vincci Maritimo',
    'Hotel Balmoral',
    'Vincci Mae',
    'Best Western Plus Hotel Felice Casati',
    'Hotel Mercure Milano Solari',
    'The Franklin Hotel Starhotels Collezione',
    'Best Western PLUS Epping Forest',
    'Hilton London Hyde Park',
    'Shaftesbury Premier London Paddington',
    'Novotel London West',
    'Barcelona Princess',
    'Renaissance Paris Republique Hotel Spa',
    'Senator Barcelona Spa Hotel',
    'Duquesa de Cardona',
    'Hotel Balmes',
    'NH Collection Barcelona Constanza',
    'Le Belmont Champs Elys es',
    'Mokinba Hotels Montebianco',
    'Monsieur Cadet Hotel Spa Ex Meyerhold Spa ',
    'UNA Maison Milano',
    'Park Grand London Lancaster Gate',
    'Ramada Plaza Milano',
    'Le 123 Elysees Astotel',
    'Le A',
    'The Beaumont Hotel',
    'Fleming s Selection Hotel Wien City',
    'La Tremoille Paris',
    'Thistle Kensington Gardens',
    'Claris Hotel Spa GL',
    'DoubleTree by Hilton Hotel London Marble Arch',
    'Royal Garden Hotel',
    'The Chamberlain',
    'Hotel d Orsay Esprit de France',
    'H10 Casanova',
    'Qualys Hotel Nasco',
    'Hotel Marconi',
    'Mercure Milano Regency',
    'Radisson Blu Portman Hotel London',
    'Excelsior Hotel Gallia Luxury Collection Hotel',
    'Monhotel Lounge SPA',
    'The Hoxton Holborn',
    'Ten Manchester Street Hotel',
    'London Marriott Hotel West India Quay',
    'Shangri La Hotel Paris',
    'Hotel Zeitgeist Vienna Hauptbahnhof',
    'Hotel Astra Opera Astotel',
    'Best Western Hotel Major',
    'Holiday Inn London Oxford Circus',
    'Grand Hotel Saint Michel',
    'Pullman Paris Montparnasse',
    'Kingsway Hall Hotel',
    'Hotel Die Port van Cleve',
    'Holiday Inn London Bloomsbury',
    'Atlantis Hotel Vienna',
    'H tel Le Royal Monceau Raffles Paris',
    'Hotel 4 Barcelona',
    'Catalonia Ramblas 4 Sup',
    'Park Grand London Kensington',
    'Novotel Paris Centre Bercy',
    'NH Amsterdam Zuid',
    'Hilton Garden Inn Milan North',
    'Hotel Arts Barcelona',
    'Villa Lut ce Port Royal',
    'Grange Buckingham Hotel',
    'H tel Fabric',
    'Room Mate Giulia',
    'St Paul s Hotel',
    'Hotel Dieci',
    'DoubleTree by Hilton London West End',
    'Hotel ViennArt am Museumsquartier',
    'Hotel Grums Barcelona',
    'Jumeirah Carlton Tower',
    'Caesar Hotel',
    'Hotel Vondel Amsterdam',
    'The Bloomsbury Hotel',
    'Sofitel London St James',
    'The Westbourne Hyde Park',
    'The Ring Vienna s Casual Luxury Hotel',
    'Four Seasons Hotel George V Paris',
    'Hotel Spadari Al Duomo',
    'Hotel Pulitzer Paris',
    'Ritz Paris',
    'Andaz London Liverpool Street',
    'Hotel Indigo London Kensington',
    'NH Collection Barcelona Gran Hotel Calder n',
    'Thistle Hyde Park',
    'Holiday Inn London Kensington',
    'Mercure Paris Montparnasse Raspail',
    'The Corner Hotel',
    'Melia Barcelona Sky 4 Sup',
    'Hotel Mercure Wien Westbahnhof',
    'Saint SHERMIN bed breakfast champagne',
    'NH Collection Amsterdam Doelen',
    'Hotel Tour d Auvergne Opera',
    'Best Western Hotel City',
    'Grange White Hall Hotel',
    'Hotel Saint Petersbourg Opera',
    'Les Plumes Hotel',
    'U232 Hotel',
    'The Square Milano Duomo',
    'Taj 51 Buckingham Gate Suites and Residences',
    'Arenas Atiram Hotels',
    'Park Lane Mews Hotel',
    'Snob Hotel by Elegancia',
    'Timhotel Op ra Blanche Fontaine',
    'Relais H tel du Vieux Paris',
    'Good Hotel London',
    'Sloane Square Hotel',
    'Montfleuri',
    'Holiday Inn London Kensington Forum',
    'Hotel Xenia Autograph Collection',
    'Hotel de Nell',
    'The Ritz London',
    'The RE London Shoreditch',
    'The Cumberland A Guoman Hotel',
    'H tel Etoile Saint Honor by Happyculture',
    'The Montcalm Marble Arch',
    'Suites H tel Helzear Montparnasse',
    'H tel Arvor Saint Georges',
    'Cotton House Hotel Autograph Collection',
    'H tel Balzac',
    'Hotel Ronda Lesseps',
    'Lyric H tel Paris',
    'Eiffel Trocad ro',
    'Crowne Plaza London Ealing',
    'COMO Metropolitan London',
    'The May Fair Hotel',
    'Renaissance Paris Vendome Hotel',
    'Lindner Hotel Am Belvedere',
    'Catalonia Atenas',
    'The Cleveland',
    'Idol Hotel',
    'Canary Riverside Plaza Hotel',
    'Goodenough Club',
    'The Hub Hotel',
    'Hilton London Paddington',
    'Golden Tulip Amsterdam West',
    'Hotel Parco di Sch nbrunn Vienna',
    'Villa Beaumarchais',
    'Shaftesbury Suites London Marble Arch',
    'Le Littr ',
    'LHP Hotel Napoleon',
    'The Piccadilly London West End',
    'H tel Mathis Elys es',
    'Mercure Paris Pigalle Sacre Coeur',
    'Hotel Beethoven Wien',
    'Nottingham Place Hotel',
    'Hotel de France Wien',
    'Le Relais Madeleine',
    'Club Quarters Hotel Gracechurch',
    'Le Grey Hotel',
    'Austria Trend Hotel Lassalle Wien',
    'Camperio House Suites Apartments',
    'Sofitel Paris Le Faubourg',
    'Hotel Auriga',
    'Royal Saint Honore',
    'Hotel Schani Wien',
    'H tel Juliana Paris',
    'H tel Saint Marc',
    'Auteuil Tour Eiffel',
    'Grand Pigalle Hotel',
    'Le Cinq Codet',
    'Idea Hotel Milano San Siro',
    'IH Hotels Milano Ambasciatori',
    'Grange Clarendon Hotel',
    'Steigenberger Hotel Herrenhof',
    'Durrants Hotel',
    'Ramada Apollo Amsterdam Centre',
    'Hidden Hotel by Elegancia',
    'Hotel Pension Baron am Schottentor',
    'Four Points Sheraton Milan Center',
    'Exe Laietana Palace',
    'Courtyard by Marriott Vienna Schoenbrunn',
    'The Soho Hotel',
    'Hotel Le Pera',
    'The Trafalgar Hilton',
    'Hotel America Barcelona',
    'Royal Passeig de Gracia',
    'Mercure Grand Hotel Biedermeier Wien',
    'La Maison Champs Elys es',
    'Acad mie H tel Saint Germain',
    'The Exhibitionist Hotel',
    'Best Western Plus 61 Paris Nation Hotel',
    'Avenida Palace',
    'H tel Westminster',
    'Senator Hotel Vienna',
    'InterContinental Wien',
    'Hotel 1898',
    'citizenM London Bankside',
    'JUFA Hotel Wien',
    'Ilunion Bel Art',
    'W Amsterdam',
    'Hotel Xanadu',
    'Rosa Grand Milano Starhotels Collezione',
    'Hilton Barcelona',
    'H tel Du Jeu De Paume',
    'Palazzo Segreti',
    'ME London by Melia',
    'Hotel Amsterdam De Roode Leeuw',
    'Room Mate Aitana',
    'Das Triest Hotel',
    'Phileas Hotel',
    'Best Western Mornington Hotel Hyde Park',
    'H tel De Castiglione',
    'Thistle Trafalgar Square The Royal Trafalgar',
    'H tel Cristal Champs Elys es',
    'Hotel Johann Strauss',
    'Mercer Hotel Barcelona',
    'Le 123 S bastopol Astotel',
    'Klima Hotel Milano Fiere',
    'The Montcalm At Brewery London City',
    'Thistle Holborn The Kingsley',
    'Holiday Inn Amsterdam',
    'Hotel Advance',
    'Amadi Panorama Hotel',
    'Hotel Indigo London Paddington',
    'The Gates Diagonal Barcelona',
    'Forest Hill Paris la Villette',
    'Mercure Hotel Amsterdam West',
    'Westside Arc de Triomphe Hotel',
    'London City Suites',
    'Kensington House Hotel',
    'R Kipling by Happyculture',
    'The Curtain',
    'Mercure London Bridge',
    'Hotel Lumen Paris Louvre',
    'Windsor Hotel Milano',
    'Hotel Domizil',
    'Radisson Blu Edwardian New Providence Wharf',
    'TownHouse Galleria',
    'H tel Le Marianne',
    'Maxim Op ra',
    'TWO Hotel Barcelona by Axel 4 Sup Adults Only',
    'NYX Milan',
    'Gardette Park Hotel',
    'Crowne Plaza Barcelona Fira Center',
    'Hotel Mercure Milano Centro',
    'Le Narcisse Blanc Spa',
    'My Bloomsbury',
    'H tel Duc De St Simon',
    'Gainsborough Hotel',
    'Holiday Inn Paris Saint Germain des Pr s',
    'Hotel Palais Strudlhof',
    'Sir Albert Hotel',
    'Paddington Court Executive Rooms',
    'H10 Itaca',
    'Holiday Inn London Camden Lock',
    'NH Collection Amsterdam Grand Hotel Krasnapolsky',
    'Hotel La Lanterne',
    'La Clef Tour Eiffel',
    'Hotel Prinz Eugen',
    'Starhotels Echo',
    'H tel de Varenne',
    'Best Western Blue Tower Hotel',
    'Hotel Galileo',
    'Le Relais M dicis',
    'Ibis Styles Paris Gare Saint Lazare',
    'Renaissance Amsterdam Hotel',
    'Mercure Paris Gobelins Place d Italie',
    'Apex London Wall Hotel',
    'Hotel Das Tigra',
    'The Mirror Barcelona',
    'Sixtytwo Hotel',
    'H tel Vernet',
    'Catalonia Port',
    'Radisson Blu Edwardian Vanderbilt',
    'Barcel Milan',
    'Best Western Plus de Neuville Arc de Triomphe',
    'Chiswick Rooms',
    'The LaLit London',
    'Hotel Duminy Vendome',
    'Victoria Palace Hotel',
    'The Goring',
    'The Bailey s Hotel London',
    'Le Marquis Eiffel',
    'Seraphine Kensington Gardens Hotel',
    'Hotel Portello Gruppo Minihotel',
    'Mercure Paris Centre Tour Eiffel',
    'Mercure Paris Champs Elys es',
    'Adria Boutique Hotel',
    'Park Hyatt Paris Vendome',
    'H tel de La Tamise Esprit de France',
    'Best Western Delphi Hotel',
    'The Zetter Hotel',
    'Bianca Maria Palace Hotel',
    'Capri by Fraser Barcelona',
    'Balmoral Champs Elys es',
    'Armani Hotel Milano',
    'Grange Wellington Hotel',
    'H tel Belloy Saint Germain By Happyculture',
    'Bloomsbury Palace Hotel',
    'Hilton London Euston',
    'Staybridge Suites London Stratford',
    'Gran Hotel Torre Catalunya',
    'Timhotel Op ra Grands Magasins',
    'Hotel Omm',
    'Villa Opera Drouot',
    'Hotel Elys es Bassano',
    'Malmaison London',
    'Hotel Spa La Belle Juliette',
    'Chateau Frontenac',
    'Rafayel Hotel Spa',
    'Hotel Dupond Smith',
    'Upper Diagonal',
    'Hotel Stefanie',
    'Mandarin Oriental Paris',
    'Mercure Barcelona Condor',
    'Hilton Amsterdam',
    'Mercure Paris Porte De Versailles Expo',
    'Hotel Casa Bonay',
    'Hotel Dei Cavalieri',
    'Draycott Hotel',
    'Mercure Paris Opera Garnier',
    'DoubleTree by Hilton London Westminster',
    'Mandarin Oriental Barcelona',
    'Boutiquehotel Das Tyrol',
    'Egerton House',
    'Select Hotel',
    'Hilton Vienna Danube Waterfront',
    'Le Pradey',
    'Mill sime H tel',
    'Molitor Paris MGallery by Sofitel',
    'Hotel Da Vinci',
    'K K H tel Cayr Saint Germain des Pr s',
    'Hotel Erzherzog Rainer',
    'Room Mate Gerard',
    'Saint James Albany Paris Hotel Spa',
    'Vienna Marriott Hotel',
    'Hotel Manin',
    'K West Hotel Spa',
    'Au Manoir Saint Germain',
    'The Cavendish London',
    'AZIMUT Hotel Vienna',
    'Le Meridien Vienna',
    'Hotel Okura Amsterdam',
    'Hotel Topazz',
    'Ace Hotel London Shoreditch',
    'NH Amsterdam Centre',
    'Best Western Plus Seraphine Hammersmith Hotel',
    'Milestone Hotel Kensington',
    'H tel Bel Ami',
    'Hotel La Place',
    'Hotel Design Secret de Paris',
    'Hotel Le Chat Noir',
    'Villa Montparnasse',
    'DoubleTree by Hilton London Hyde Park',
    'Novotel London Waterloo',
    'Abba Garden',
    'The Ritz Carlton Vienna',
    'Best Western Hotel Montmartre Sacr Coeur',
    'Holiday Inn Paris Gare de Lyon Bastille',
    'Mercure Hotel Amsterdam Centre Canal District',
    'Enterprise Hotel Design Boutique',
    '88 Studios',
    'HCC St Moritz',
    'Eurostars Bcn Design',
    'Ohla Eixample',
    'Montcalm Royal London House City of London',
    'Crowne Plaza London Battersea',
    'Alma Boutique Hotel',
    'Hilton Garden Inn Vienna South',
    'Catalonia Passeig de Gr cia 4 Sup',
    'Mokinba Hotels King',
    'Hotel The Serras',
    'Strandhotel Alte Donau',
    'Ch teau Monfort Relais Ch teaux',
    'Artus Hotel by MH',
    'Strand Palace Hotel',
    'Hyatt Regency Amsterdam',
    'Hotel Spa Villa Olimpica Suites',
    'Starhotels Ritz',
    'Rochester Champs Elysees',
    'Atahotel Linea Uno',
    'Le Tourville Eiffel',
    'H tel Paris Bastille Boutet MGallery by Sofitel',
    'Hotel Daniel Paris',
    'Hotel Seven One Seven',
    'Chasse Hotel',
    'H tel Regent s Garden',
    'Novotel Wien City',
    'Swiss tel Amsterdam',
    'BEST WESTERN Maitrise Hotel Maida Vale',
    'Gartenhotel Altmannsdorf Hotel 1',
    'Radisson Blu Hotel Milan',
    'Andaz Amsterdam Prinsengracht A Hyatt Hotel',
    'Residence Du Roy',
    'Melia Barcelona Sarri ',
    'Best Western Hotel Pension Arenberg Wien Zentrum',
    'The Colonnade',
    'The Marble Arch London',
    'Hotel Maison FL',
    'Eurostars Monumental',
    'Grange Blooms Hotel',
    'Hotel Regina',
    'Best Western S vres Montparnasse',
    'H tel La Comtesse by Elegancia',
    'Hotel L Antoine',
    'Crowne Plaza Milan City',
    'Amsterdam Marriott Hotel',
    'Radisson Blu Edwardian Sussex',
    'Catalonia Eixample 1864',
    'D clic Hotel',
    'IH Hotels Milano Puccini',
    'H tel Les Dames du Panth on',
    'Buddha Bar Hotel Paris',
    'every hotel Piccadilly',
    'Catalonia Magdalenes',
    'Hilton London Olympia',
    'Le 7 Eiffel Hotel',
    'Hotel Atlanta',
    'Hotel VIU Milan',
    'H tel Exquis by Elegancia',
    'St George s Hotel Wembley',
    'Best Western Premier Trocadero La Tour',
    'K K Hotel George',
    'The Premier Notting Hill',
    'Holiday Inn London Brent Cross',
    'Sofitel Paris Baltimore Tour Eiffel',
    'Grange Rochester Hotel',
    'NH Collection Barcelona Podium',
    'W Paris Op ra',
    'The Ned',
    'Crowne Plaza London Kings Cross',
    'Amarante Champs Elys es',
    '45 Park Lane Dorchester Collection',
    'H tel Regina Op ra Grands Boulevards',
    'Roger de Ll ria',
    'Chambiges Elys es',
    'Francois 1er',
    'The London EDITION',
    'Victoires Opera',
    'Hotel Royal',
    'H tel L Echiquier Op ra Paris MGallery by Sofitel',
    'Grange City Hotel',
    'Bradford Elys es Astotel',
    'WestCord Fashion Hotel Amsterdam',
    'Gallery Hotel',
    'Hotel Square',
    'INK Hotel Amsterdam MGallery by Sofitel',
    'Montagu Place Hotel',
    'Hotel The Peninsula Paris',
    'Vice Versa',
    'Hotel Gallitzinberg',
    'Arthotel ANA Boutique Six',
    'Ako Suites Hotel',
    'Hotel Raffaello',
    'The Cranley Hotel',
    'Best Western Ducs de Bourgogne',
    'Le Relais Montmartre',
    'H tel Le Bellechasse Saint Germain',
    'The Lodge Hotel Putney',
    'Golden Tulip Opera de Noailles',
    'DoubleTree by Hilton London Victoria',
    'Petit Palais Hotel De Charme',
    'Cram',
    'Fielding Hotel',
    'The Yard Milano',
    'Simm s Hotel',
    'Hotel Marignan Champs Elys es',
    'H tel Bourgogne Montana by MH',
    'Crowne Plaza Paris R publique',
    'Aloft London Excel',
    'Ozo Hotel',
    'The Marylebone Hotel',
    'NH Barcelona Stadium',
    'Fifty Four Boutique Hotel',
    'Austria Trend Hotel Rathauspark Wien',
    'Zenit Borrell',
    'H tel Champs lys es Plaza',
    'H tel Th r se',
    'Hotel Liberty',
    'Hotel Les Th tres',
    'Leonardo Hotel Vienna',
    'Hotel Maison Ath n e',
    'Mercure Vaugirard Paris Porte De Versailles',
    'Gran Hotel Barcino',
    'NH Amsterdam Schiller',
    'Baglioni Hotel London The Leading Hotels of the World',
    'Hotel Claridge Paris',
    'Holiday Inn Paris Gare de l Est',
    'Hampshire Hotel Rembrandt Square Amsterdam',
    'Drawing Hotel',
    'H tel de Jos phine BONAPARTE',
    'Hotel Sanpi Milano',
    'Radisson Blu Hotel Amsterdam',
    'The Pelham Starhotels Collezione',
    'DoubleTree by Hilton London Docklands Riverside',
    'La Villa Maillot',
    'Staybridge Suites London Vauxhall',
    'Hotel Barcelona Center',
    'H tel Hor',
    'H tel Duo',
    'The Whitechapel',
    'H tel Aiglon Esprit de France',
    'Cordial Theaterhotel Wien',
    'Grand H tel Du Palais Royal',
    'Sunotel Central',
    'London Marriott Hotel County Hall',
    'Hotel Park Lane Paris',
    'Great St Helen Hotel',
    'Mercure Tour Eiffel Grenelle',
    'Four Seasons Hotel London at Park Lane',
    'The Lanesborough',
    'Le Dokhan s a Tribute Portfolio Hotel',
    'InterContinental Paris Le Grand',
    'Vienna Sporthotel',
    'The Westbury A Luxury Collection Hotel Mayfair London',
    'Le Roch Hotel Spa',
    'Renaissance Paris Le Parc Trocadero Hotel',
    'Hotel OFF Paris Seine',
    'The Stafford London',
    'De Vere Devonport House',
    'Antares Hotel Rubens',
    'Pestana Arena Barcelona',
    'Attica 21 Barcelona Mar',
    'St Ermin s Hotel Autograph Collection',
    'ADI Hotel Poliziano Fiera',
    'H tel Saint Paul Rive Gauche',
    'Hotel Le Squara',
    'Appartement Hotel an der Riemergasse',
    'Pillows Anna van den Vondel Amsterdam',
    'Nell Hotel Suites',
    'Austria Trend Hotel Bosei Wien',
    'Hyatt Regency London The Churchill',
    'H tel des Academies et des Arts',
    'Waldorf Madeleine',
    'InterContinental Paris Avenue Marceau',
    'Best Western Le Jardin de Cluny',
    'Hotel Oscar',
    'pentahotel Vienna',
    'Hotel Mercure La Sorbonne Saint Germain des Pr s',
    'HCC Regente',
    'Hotel du Collectionneur Arc de Triomphe',
    'Le Mathurin Hotel Spa',
    'Art Hotel Navigli',
    'Sunotel Club Central',
    'Arbor City',
    'Hotel Lam e',
    'The Wellesley Knightsbridge a Luxury Collection Hotel London',
    '41',
    'Arbor Hyde Park',
    'DoubleTree by Hilton Hotel Amsterdam NDSM Wharf',
    'Mercure Paris Place d Italie',
    'Grand Hotel et de Milan',
    'Novotel Suites Paris Montreuil Vincennes',
    'Park Hyatt Milano',
    'Grange Tower Bridge Hotel',
    'Boutique Hotel Notting Hill',
    'The Nadler Soho',
    'ME Milan Il Duca',
    'Hotel Granados 83',
    'Hotel Romana Residence',
    'Golden Tulip Amsterdam Riverside',
    'The Kensington Hotel',
    'Colombia',
    'Starhotels Tourist',
    'Pullman Barcelona Skipper',
    'L Edmond H tel',
    'Royal Amsterdam Hotel',
    'Best Western Hotel St George',
    'Windermere Hotel',
    'Best Western Nouvel Orl ans Montparnasse',
    'Albus Hotel Amsterdam City Centre',
    'Knightsbridge Hotel',
    'Hotel Neri',
    'Mercure Amsterdam Sloterdijk Station',
    'Le Saint Hotel Paris',
    'Novotel Paris Centre Gare Montparnasse',
    'Hotel Am Stephansplatz',
    'Club Hotel Cortina',
    'Park Plaza Sherlock Holmes London',
    'Hotel Lloyd',
    'H tel Concorde Montparnasse',
    'Maison Souquet',
    'NH London Kensington',
    'Radisson Blu Champs Elys es Paris',
    'Austria Trend Parkhotel Sch nbrunn Wien',
    'Mercure Paris Alesia',
    'Banks Mansion All Inclusive Hotel',
    'Primero Primera',
    '25hours Hotel beim MuseumsQuartier',
    'H tel Jos phine by Happyculture',
    'UNA Hotel Century',
    'Acta CITY47',
    'Clayton Hotel Chiswick',
    'Mercer House B ria BCN',
    'H tel Pont Royal',
    'Hotel Mailberger Hof',
    'NH Milano Machiavelli',
    'Le M ridien Etoile',
    'The Berkeley',
    'Tryp Barcelona Condal Mar Hotel',
    'Col n Hotel Barcelona',
    'Best Western Op ra Batignolles',
    'Best Western Hotel Astoria',
    'H tel de Banville',
    'Best Western Premier Op ra Li ge',
    'NH Wien Belvedere',
    'Edouard 7 Paris Op ra',
    'Hotel West End',
    'Hotel Whistler',
    'Holiday Inn Paris Montparnasse Pasteur',
    'Amp re',
    'London Marriott Hotel Marble Arch',
    'Novotel London Paddington',
    'InterContinental London Park Lane',
    'H tel Regina',
    'Hotel Georgette',
    'NH Wien City',
    'Hilton Milan',
    'Megaro Hotel',
    'Hotel Bellevue Wien',
    'Novotel Paris Les Halles',
    'Hotel Park Villa',
    'H10 Port Vell 4 Sup',
    'Hotel Montaigne',
    'Corendon Vitality Hotel Amsterdam',
    'Bentley London',
    'Banke H tel',
    'Hotel Front Maritim',
    'Villa Eugenie',
    'Little Palace Hotel',
    'The Royal Horseguards',
    'Oceania Paris Porte De Versailles',
    'Sansi Pedralbes',
    'Claridge s',
    'Courthouse Hotel Shoreditch',
    'Hotel Chavanel',
    'Holiday Inn Milan Garibaldi Station',
    'K K Palais Hotel',
    'Mercure London Paddington Hotel',
    'K K Hotel Picasso',
    'Eurostars Cristal Palace',
    'Hotel De Hallen',
    'Holiday Inn London Stratford City',
    'Park Plaza Westminster Bridge London',
    'The Hoxton Amsterdam',
    'Nolinski Paris',
    'Novotel London Wembley',
    'Hotel Monceau Wagram',
    'Hotel Principe Di Savoia',
    'Dorset Square Hotel',
    'Mercure Josefshof Wien',
    'Hotel Cafe Royal',
    'Sofitel Paris Arc De Triomphe',
    'H tel La Parizienne by Elegancia',
    'Arioso',
    'Mercure Hotel Amsterdam City South',
    'Hotel Crivi s',
    'Sydney House Chelsea',
    'Grand Visconti Palace',
    'Mimi s Hotel Soho',
    'Medinaceli',
    'Eurostars Grand Marina Hotel GL',
    'Hotel Derby',
    'Renaissance Paris Arc de Triomphe Hotel',
    'Avo Hotel',
    'Novotel London Tower Bridge',
    'Occidental Atenea Mar Adults Only',
    'Vincci Gala',
    'Pestana Chelsea Bridge Hotel Spa',
    'Uptown Palace',
    'Austria Trend Hotel Anatol Wien',
    'Savoy Hotel Amsterdam',
    'Austria Trend Hotel Ananas Wien',
    'Hotel Vilamar ',
    'AC Hotel Milano a Marriott Lifestyle Hotel',
    'AC Hotel Victoria Suites a Marriott Lifestyle Hotel',
    'Bassano',
    'H tel Square Louvois',
    'Golden Tulip Washington Opera',
    'IH Hotels Milano Watt 13',
    'art otel Amsterdam',
    'Best Western Hotel Ascot',
    'Catalonia Diagonal Centro',
    'Boscolo Milano Autograph Collection',
    'Nhow Milan',
    'Commodore Hotel',
    'The Pillar Hotel',
    'Relais Saint Jacques'
    ];

}